"use client";
import { useEffect,useState } from "react";

export default function AdminOperations(){
 const [users,setUsers]=useState<any[]>([]);const [purges,setPurges]=useState<any[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const load=async()=>{const [u,p]=await Promise.all([fetch("/api/admin/roles",{cache:"no-store"}),fetch("/api/admin/purge-requests",{cache:"no-store"})]);const [uj,pj]=await Promise.all([u.json(),p.json()]);if(u.ok)setUsers(uj.users||[]);if(p.ok)setPurges(pj.requests||[]);};
 useEffect(()=>{void load()},[]);
 const role=async(userId:string,nextRole:string,active=true)=>{setBusy(true);const r=await fetch("/api/admin/roles",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId,role:nextRole,active})});const j=await r.json();setMessage(r.ok?"Role updated.":j.error||"Role update failed.");setBusy(false);if(r.ok)await load();};
 const purge=async(id:string,action:string)=>{setBusy(true);const r=await fetch(`/api/purge-requests/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,reason:action==="REJECT"?"Rejected by records administrator":""})});const j=await r.json();setMessage(r.ok?`Purge request ${action.toLowerCase()}d.`:j.error||"Purge action failed.");setBusy(false);if(r.ok)await load();};
 return <main style={{maxWidth:1300,margin:"16px auto 40px",padding:"0 30px",fontFamily:"system-ui",color:"#17212b"}}>{message&&<div style={notice}>{message}</div>}<section style={panel}><h2>Authenticated users and application roles</h2><p style={hint}>Users appear after their first successful Entra sign-in. VIEWER is the implicit role until an explicit role is granted.</p><div style={{overflow:"auto"}}><table style={table}><thead><tr><th style={th}>Identity</th><th style={th}>Current role</th><th style={th}>Grant role</th><th style={th}>Explicit</th></tr></thead><tbody>{users.map(u=><tr key={u.user_id}><td style={td}><b>{u.name||"Unnamed user"}</b><br/><small>{u.email}</small></td><td style={td}>{u.role}</td><td style={td}><select disabled={busy} value={u.role} onChange={e=>void role(u.user_id,e.target.value,true)}>{["VIEWER","LAWYER","APPROVER","ADMIN"].map(r=><option key={r}>{r}</option>)}</select></td><td style={td}>{u.role_explicit?"YES":"NO"}</td></tr>)}</tbody></table></div></section><section style={{...panel,marginTop:16}}><h2>Records purge authority queue</h2><p style={hint}>Purge requires an expired retention date, no legal hold, independent Admin approval, and the production purge switch. Metadata and audit history remain after object deletion.</p>{purges.length?<div style={{display:"grid",gap:10}}>{purges.map(p=><article style={card} key={p.id}><div><b>{p.customer} · {p.matter_number}</b><div style={hint}>{p.filename} · requested by {p.requested_by_email||p.requested_by}</div><p style={{fontSize:12}}>{p.reason}</p><small>Status: {p.status} · retention: {String(p.document_retention||p.matter_retention||"not set").slice(0,10)} · hold: {(p.document_hold||p.matter_hold)?"ACTIVE":"none"}</small></div><div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{p.status==="PENDING"&&<><button disabled={busy} onClick={()=>void purge(p.id,"APPROVE")}>Approve</button><button disabled={busy} onClick={()=>void purge(p.id,"REJECT")}>Reject</button></>}{p.status==="APPROVED"&&<button disabled={busy} onClick={()=>void purge(p.id,"EXECUTE")}>Execute purge</button>}</div></article>)}</div>:<p style={hint}>No purge requests.</p>}</section></main>;
}
const panel:React.CSSProperties={background:"white",border:"1px solid #e0e5ea",borderRadius:12,padding:20};const table:React.CSSProperties={width:"100%",borderCollapse:"collapse",fontSize:12};const th:React.CSSProperties={textAlign:"left",padding:8,borderBottom:"1px solid #dfe5ea",color:"#687683"};const td:React.CSSProperties={padding:8,borderBottom:"1px solid #edf0f2"};const hint:React.CSSProperties={fontSize:11,color:"#74808a"};const card:React.CSSProperties={border:"1px solid #e2e7eb",borderRadius:9,padding:12,display:"flex",justifyContent:"space-between",gap:16,alignItems:"center"};const notice:React.CSSProperties={padding:10,border:"1px solid #e0ce8d",background:"#fff7d7",borderRadius:8,marginBottom:12,fontSize:12};
