"use client";
import { useEffect,useState } from "react";

const families=["forecasting_demand","purchase_orders","pricing_repricing","raw_materials","long_lead_ncnr","consigned_inventory","title_risk_of_loss","safety_stock","excess_obsolete_inventory","engineering_changes","quality_acceptance_audits","delivery_incoterms_logistics","payment_terms","warranty","indemnity","liability_cap","termination","force_majeure","regulatory_change","sustainability"];
export default function AdminConsole(){
 const [readiness,setReadiness]=useState<any>(null);const [validation,setValidation]=useState<any>(null);const [standards,setStandards]=useState<any[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const [form,setForm]=useState({clauseFamily:"payment_terms",title:"",standardPosition:"",fallbackPosition:"",noGoPosition:"",approvalAuthority:"",businessRationale:"",version:"1.0",effectiveDate:new Date().toISOString().slice(0,10)});
 const refresh=async()=>{const [r,v,s]=await Promise.all([fetch("/api/readiness",{cache:"no-store"}),fetch("/api/validation/latest",{cache:"no-store"}),fetch("/api/standards",{cache:"no-store"})]);const [rj,vj,sj]=await Promise.all([r.json(),v.json(),s.json()]);if(r.ok)setReadiness(rj.readiness);if(v.ok)setValidation(vj.validation);if(s.ok)setStandards(sj.standards||[]);};
 useEffect(()=>{void refresh()},[]);
 const runValidation=async()=>{setBusy(true);setMessage("");const r=await fetch("/api/validation/run",{method:"POST"});const j=await r.json();setMessage(r.ok?`Validation workflow started: ${j.runId}`:j.error||"Unable to start validation.");setBusy(false);};
 const createStandard=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);const r=await fetch("/api/standards",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();setMessage(r.ok?"Standard created inactive. Review before activation.":j.error||"Unable to create standard.");setBusy(false);if(r.ok)await refresh();};
 const activate=async(id:string)=>{setBusy(true);const r=await fetch(`/api/standards/${id}/activate`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({confirm:true})});const j=await r.json();setMessage(r.ok?`Activated ${j.clauseFamily} ${j.version}.`:j.error||"Activation failed.");setBusy(false);if(r.ok)await refresh();};
 return <main style={{maxWidth:1300,margin:"0 auto",padding:30,fontFamily:"system-ui",color:"#17212b"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"end"}}><div><a href="/" style={{color:"#53606d",fontSize:12}}>← Executive cockpit</a><div style={{fontSize:11,fontWeight:800,letterSpacing:".12em",color:"#607080",marginTop:12}}>ADMIN · GOVERNANCE</div><h1 style={{margin:"5px 0"}}>ContractTwin production control plane</h1><p style={{color:"#6a7783"}}>Identity, infrastructure, validation evidence and approved negotiation standards.</p></div><button onClick={()=>void refresh()}>Refresh</button></div>{message&&<div style={{padding:10,background:"#fff7d5",border:"1px solid #e6d48c",borderRadius:8,margin:"14px 0"}}>{message}</div>}
 <section style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginTop:20}}><div style={panel}><h2>Production readiness</h2>{readiness?<><Grid items={[["Entra SSO",readiness.configured?.authenticationRequired&&readiness.configured?.microsoftConfigured],["PostgreSQL",readiness.configured?.databaseConfigured],["Private Blob",readiness.configured?.privateBlobConfigured],["OpenAI",readiness.configured?.aiConfigured],["Azure OCR",readiness.configured?.ocrConfigured],["Current validation",readiness.validationPassed],["Standards coverage",(readiness.missingStandards?.length||0)===0]]}/><p><b>Legal reliance ready:</b> {readiness.legalRelianceReady?"YES":"NO"}</p>{readiness.missingStandards?.length>0&&<p style={{fontSize:12,color:"#7a4d2e"}}>Missing active standards: {readiness.missingStandards.join(", ")}</p>}</>:<p>Readiness unavailable.</p>}</div>
 <div style={panel}><h2>Frozen legal validation</h2>{validation?<><p><b>Status:</b> {validation.status}</p><p><b>Model:</b> {validation.model_name} · <b>Corpus:</b> {validation.corpus_version}</p><p><b>Family recall:</b> {(Number(validation.family_recall||0)*100).toFixed(1)}% · <b>Grounding:</b> {(Number(validation.grounded_precision||0)*100).toFixed(1)}%</p><p><b>Passed cases:</b> {validation.passed_cases}/{validation.total_cases}</p></>:<p>No persisted production validation run.</p>}<button disabled={busy} onClick={()=>void runValidation()} style={primary}>Run current frozen validation suite</button></div></section>
 <section style={{...panel,marginTop:16}}><h2>Negotiation standards registry</h2><div style={{overflow:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr><th style={th}>Clause family</th><th style={th}>Title / version</th><th style={th}>State</th><th style={th}>Authority</th><th style={th}></th></tr></thead><tbody>{standards.map(s=><tr key={s.id}><td style={td}>{s.clause_family}</td><td style={td}><b>{s.title}</b><br/><small>{s.version} · {s.effective_date}</small></td><td style={td}>{s.active?"ACTIVE / APPROVED":"INACTIVE"}</td><td style={td}>{s.approval_authority||"—"}</td><td style={td}>{!s.active&&<button disabled={busy} onClick={()=>void activate(s.id)}>Activate with explicit confirmation</button>}</td></tr>)}</tbody></table></div></section>
 <section style={{...panel,marginTop:16}}><h2>Create controlled standard</h2><p style={{fontSize:12,color:"#6a7783"}}>New standards are always inactive. Activation is a separate audited Admin action.</p><form onSubmit={createStandard} style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}><Field label="Clause family"><select value={form.clauseFamily} onChange={e=>setForm({...form,clauseFamily:e.target.value})}>{families.map(f=><option key={f}>{f}</option>)}</select></Field><Field label="Title"><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Standard position"><textarea required value={form.standardPosition} onChange={e=>setForm({...form,standardPosition:e.target.value})}/></Field><Field label="Fallback"><textarea value={form.fallbackPosition} onChange={e=>setForm({...form,fallbackPosition:e.target.value})}/></Field><Field label="No-go"><textarea value={form.noGoPosition} onChange={e=>setForm({...form,noGoPosition:e.target.value})}/></Field><Field label="Approval authority"><input value={form.approvalAuthority} onChange={e=>setForm({...form,approvalAuthority:e.target.value})}/></Field><Field label="Business rationale"><textarea value={form.businessRationale} onChange={e=>setForm({...form,businessRationale:e.target.value})}/></Field><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8}}><Field label="Version"><input value={form.version} onChange={e=>setForm({...form,version:e.target.value})}/></Field><Field label="Effective date"><input type="date" value={form.effectiveDate} onChange={e=>setForm({...form,effectiveDate:e.target.value})}/></Field></div><button disabled={busy} type="submit" style={{...primary,gridColumn:"1/-1"}}>Create inactive standard</button></form></section></main>;
}
const panel:React.CSSProperties={background:"white",border:"1px solid #e0e5ea",borderRadius:12,padding:20};const primary:React.CSSProperties={background:"#17212b",color:"white",border:0,borderRadius:8,padding:"9px 12px",fontWeight:800};const th:React.CSSProperties={textAlign:"left",borderBottom:"1px solid #dfe5ea",padding:8,color:"#697683"};const td:React.CSSProperties={borderBottom:"1px solid #edf0f2",padding:8,verticalAlign:"top"};
function Grid({items}:{items:[string,boolean][]}){return <div>{items.map(([l,ok])=><div key={l} style={{display:"flex",justifyContent:"space-between",borderBottom:"1px solid #edf0f2",padding:"8px 0",fontSize:12}}><span>{l}</span><b style={{color:ok?"#176546":"#9b3434"}}>{ok?"READY":"BLOCKED"}</b></div>)}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{fontSize:11,fontWeight:700}}>{label}<div style={{marginTop:5}}>{children}</div><style jsx>{`input,select,textarea{width:100%;box-sizing:border-box;padding:8px;border:1px solid #d5dce3;border-radius:7px;font:inherit}textarea{min-height:72px}`}</style></label>}
