"use client";

import { useEffect, useMemo, useState } from "react";

type View = "overview" | "matters" | "intake" | "risk" | "economics" | "approvals";
type Risk = "Low" | "Medium" | "High" | "Critical";
type Matter = { id:string; customer:string; agreement:string; region:string; revenue:number; stage:string; risk:Risk; nextAction:string };
type Finding = { issue:string; risk:Risk; rationale:string; primaryPosition:string; fallback:string; approval:string; sourceExcerpt:string };
type EconomicsResult = { incrementalReceivable:number; workingCapitalCost:number; strandedInventoryExposure:number; warrantyReserve:number; terminationExposure:number; liabilityCapGap:number; grossProfit:number; totalModeledBurden:number; burdenAsPctOfGrossProfit:number };

const seedMatters:Matter[] = [
  {id:"CT-1042",customer:"Apex Mobility",agreement:"Global Manufacturing Services Agreement",region:"Americas",revenue:248000000,stage:"Customer redline",risk:"High",nextAction:"Resolve E&O and termination inventory"},
  {id:"CT-1038",customer:"Helios Systems",agreement:"Strategic Supply Agreement",region:"EMEA",revenue:132000000,stage:"Negotiation",risk:"Critical",nextAction:"Escalate liability cap and warranty tail"},
  {id:"CT-1033",customer:"Northstar Home",agreement:"EMS Master Agreement",region:"Americas",revenue:88000000,stage:"Renewal",risk:"Medium",nextAction:"Reprice payment-term economics"},
  {id:"CT-1029",customer:"Orion Medical",agreement:"Manufacturing SOW",region:"APAC",revenue:61000000,stage:"Approved",risk:"Low",nextAction:"Finalize signature package"}
];

const nav:[View,string][] = [["overview","Overview"],["matters","Matters"],["intake","Contract Intake"],["risk","Clause Risk"],["economics","Economics"],["approvals","Approvals"]];
const money=(v:number,compact=false)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:compact?1:0,notation:compact?"compact":"standard"}).format(v);

function RiskBadge({risk}:{risk:Risk}){return <span className={`risk risk-${risk.toLowerCase()}`}>{risk}</span>}
function Metric({label,value,note,tone=""}:{label:string;value:string;note:string;tone?:string}){return <div className={`metric ${tone}`}><div className="metric-label">{label}</div><div className="metric-value">{value}</div><div className="metric-note">{note}</div></div>}

function Overview({matters,onNavigate}:{matters:Matter[];onNavigate:(v:View)=>void}){
  const revenue=matters.reduce((s,m)=>s+m.revenue,0);
  return <div className="stack">
    <section className="hero-panel"><div><div className="eyebrow">EXECUTIVE CONTROL CENTER</div><h1>Commercial legal decisions, translated into business consequences.</h1><p>Prioritize agreements that can move margin, working capital, inventory exposure and executive risk.</p></div><button className="primary" onClick={()=>onNavigate("intake")}>New contract review</button></section>
    <section className="metrics-grid"><Metric label="Revenue under review" value={money(revenue,true)} note={`${matters.length} active matters`}/><Metric label="High / critical matters" value={String(matters.filter(m=>m.risk==="High"||m.risk==="Critical").length)} note="Need executive attention" tone="warn"/><Metric label="Modeled exposure" value="$31.8M" note="Illustrative portfolio scenario" tone="danger"/><Metric label="Decisions pending" value="5" note="2 require Finance / BU approval"/></section>
    <section className="two-col"><div className="panel"><div className="panel-head"><div><div className="eyebrow">PORTFOLIO</div><h2>Priority matters</h2></div><button className="text-button" onClick={()=>onNavigate("matters")}>View all</button></div><div className="matter-list">{matters.slice(0,3).map(m=><div className="matter-row" key={m.id}><div><strong>{m.customer}</strong><span>{m.agreement}</span></div><div className="matter-meta"><RiskBadge risk={m.risk}/><strong>{money(m.revenue,true)}</strong></div></div>)}</div></div>
    <div className="panel"><div className="eyebrow">WHERE VALUE LEAKS</div><h2>Clause exposure heat map</h2><div className="heatmap">{[["Inventory / E&O","Critical",92],["Liability cap","High",81],["Payment terms","High",77],["Warranty","Medium",62],["Termination","High",73],["Pricing adjustment","Medium",58]].map(([label,level,width])=><div className="heat-row" key={String(label)}><span>{label}</span><div className="heat-track"><i style={{width:`${width}%`}} className={`heat-${String(level).toLowerCase()}`}/></div><b>{level}</b></div>)}</div></div></section>
    <section className="panel flow-panel"><div><div className="eyebrow">CONTRACTTWIN LOGIC</div><h2>From language to action</h2></div><div className="flow"><div>Contract language</div><span>→</span><div>Operational obligation</div><span>→</span><div>Financial consequence</div><span>→</span><div>Negotiation position</div><span>→</span><div>Executive decision</div></div></section>
  </div>
}

function Matters({matters}:{matters:Matter[]}){return <section className="panel"><div className="page-title"><div><div className="eyebrow">PORTFOLIO WORKBENCH</div><h1>Contract matters</h1><p>Track commercial position, financial significance and next decision.</p></div><div className="filter-chip">Synthetic data</div></div><div className="table-wrap"><table><thead><tr><th>Matter</th><th>Customer / agreement</th><th>Revenue</th><th>Stage</th><th>Risk</th><th>Next action</th></tr></thead><tbody>{matters.map(m=><tr key={m.id}><td><strong>{m.id}</strong><small>{m.region}</small></td><td><strong>{m.customer}</strong><small>{m.agreement}</small></td><td>{money(m.revenue,true)}</td><td>{m.stage}</td><td><RiskBadge risk={m.risk}/></td><td>{m.nextAction}</td></tr>)}</tbody></table></div></section>}

function Intake({addMatter}:{addMatter:(m:Matter)=>void}){
  const [customer,setCustomer]=useState(""); const [agreement,setAgreement]=useState(""); const [region,setRegion]=useState("Americas"); const [revenue,setRevenue]=useState("100000000"); const [file,setFile]=useState(""); const [saved,setSaved]=useState(false);
  const submit=(e:React.FormEvent)=>{e.preventDefault(); if(!customer||!agreement)return; addMatter({id:`CT-${Math.floor(1100+Math.random()*800)}`,customer,agreement,region,revenue:Number(revenue)||0,stage:"Intake",risk:"Medium",nextAction:"Complete source-grounded review"}); setSaved(true)};
  return <div className="two-col intake-layout"><section className="panel"><div className="eyebrow">NEW MATTER</div><h1>Contract intake</h1><p className="subtle">Capture the minimum information needed to open a review. Files are not uploaded in this first Vercel MVP.</p><form className="form-grid" onSubmit={submit}><label>Customer<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Customer name"/></label><label>Agreement<input value={agreement} onChange={e=>setAgreement(e.target.value)} placeholder="MSA, SOW, amendment…"/></label><label>Region<select value={region} onChange={e=>setRegion(e.target.value)}><option>Americas</option><option>EMEA</option><option>APAC</option></select></label><label>Annual revenue<input type="number" value={revenue} onChange={e=>setRevenue(e.target.value)}/></label><label className="full">Source file<input type="file" accept=".pdf,.doc,.docx,.txt" onChange={e=>setFile(e.target.files?.[0]?.name||"")}/><small>{file?`Selected metadata: ${file}`:"Do not upload confidential agreements until secure storage is configured."}</small></label><button className="primary full" type="submit">Create review matter</button>{saved&&<div className="success full">Matter created in this browser.</div>}</form></section><aside className="panel"><div className="eyebrow">REVIEW GATE</div><h2>Before analysis</h2><ol className="checklist"><li>Confirm executed/current document set.</li><li>Identify MSA, SOW, amendments and exhibits.</li><li>Confirm document precedence.</li><li>Separate contract facts from business assumptions.</li><li>Require human legal validation before business reliance.</li></ol></aside></div>
}

function RiskAnalyzer(){
  const [text,setText]=useState("Customer may terminate this Agreement for convenience upon thirty (30) days' notice. Supplier shall remain responsible for all excess inventory and non-cancelable, non-returnable commitments. Payment terms are Net 90. Supplier liability is unlimited for all claims, including consequential damages and lost profits.");
  const [findings,setFindings]=useState<Finding[]>([]); const [status,setStatus]=useState(""); const [loading,setLoading]=useState(false);
  const analyze=async()=>{setLoading(true);setStatus("");try{const r=await fetch("/api/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text})});const j=await r.json();setFindings(j.findings||[]);setStatus(j.mode==="ai"?`AI analysis · ${j.rejectedUngroundedFindings||0} ungrounded findings rejected`:`${j.mode||"triage"} · ${j.warning||"Human review required"}`)}catch{setStatus("Analysis service unavailable.")}finally{setLoading(false)}};
  return <div className="stack"><section className="panel"><div className="page-title"><div><div className="eyebrow">SOURCE-GROUNDED TRIAGE</div><h1>Clause risk analyzer</h1><p>Paste contract text. Every output remains unreviewed until a lawyer validates it.</p></div><span className="filter-chip">Human review required</span></div><textarea className="clause-box" value={text} onChange={e=>setText(e.target.value)}/><div className="action-row"><button className="primary" onClick={analyze} disabled={loading}>{loading?"Analyzing…":"Analyze text"}</button><span className="subtle">{status}</span></div></section>{findings.length>0&&<section className="findings-grid">{findings.map((f,i)=><article className="finding panel" key={`${f.issue}-${i}`}><div className="finding-top"><strong>{f.issue}</strong><RiskBadge risk={f.risk}/></div><p>{f.rationale}</p><div className="source"><span>SOURCE</span>“{f.sourceExcerpt}”</div><dl><dt>Primary position</dt><dd>{f.primaryPosition}</dd><dt>Fallback</dt><dd>{f.fallback}</dd><dt>Approval</dt><dd>{f.approval}</dd></dl><button className="secondary">Mark for legal review</button></article>)}</section>}</div>
}

const defaults={annualRevenue:250000000,grossMarginPct:8,paymentDays:90,baselinePaymentDays:45,carryingCostPct:10,inventoryOnHand:18000000,ncnrExposure:6000000,forecastReductionPct:40,warrantyRatePct:.6,terminationCoveragePct:35,liabilityCap:15000000,modeledClaim:28000000};
function Economics(){
 const [inputs,setInputs]=useState(defaults); const [result,setResult]=useState<EconomicsResult|null>(null); const update=(k:keyof typeof inputs,v:string)=>setInputs(p=>({...p,[k]:Number(v)}));
 const calculate=async()=>{const r=await fetch("/api/economics",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(inputs)});const j=await r.json();setResult(j.result)}; useEffect(()=>{void calculate()},[]);
 const fields:[keyof typeof inputs,string,string][]=[["annualRevenue","Annual revenue","$"],["grossMarginPct","Gross margin","%"],["paymentDays","Customer payment days","days"],["baselinePaymentDays","Baseline payment days","days"],["carryingCostPct","Carrying cost","%"],["inventoryOnHand","Inventory on hand","$"],["ncnrExposure","NCNR commitments","$"],["forecastReductionPct","Forecast reduction","%"],["warrantyRatePct","Warranty reserve rate","%"],["terminationCoveragePct","Termination recovery coverage","%"],["liabilityCap","Liability cap","$"],["modeledClaim","Modeled claim","$"]];
 return <div className="economics-layout"><section className="panel"><div className="eyebrow">DETERMINISTIC MODEL</div><h1>Contract economics simulator</h1><p>Contract facts and business assumptions stay separate. Calculations are ordinary software, not LLM arithmetic.</p><div className="input-grid">{fields.map(([k,l,u])=><label key={k}>{l}<div className="input-with-unit"><input type="number" value={inputs[k]} onChange={e=>update(k,e.target.value)}/><span>{u}</span></div></label>)}</div><button className="primary" onClick={calculate}>Recalculate exposure</button></section><section className="panel results-panel"><div className="eyebrow">MODELED CONSEQUENCES</div><h2>Current scenario</h2>{result&&<><div className="result-total"><span>Total modeled burden</span><strong>{money(result.totalModeledBurden,true)}</strong><small>{result.burdenAsPctOfGrossProfit.toFixed(1)}% of modeled gross profit</small></div><div className="result-list"><div><span>Incremental receivable</span><b>{money(result.incrementalReceivable,true)}</b></div><div><span>Annual working-capital cost</span><b>{money(result.workingCapitalCost,true)}</b></div><div><span>Stranded inventory</span><b>{money(result.strandedInventoryExposure,true)}</b></div><div><span>Termination exposure</span><b>{money(result.terminationExposure,true)}</b></div><div><span>Warranty reserve</span><b>{money(result.warrantyReserve,true)}</b></div><div><span>Liability cap gap</span><b>{money(result.liabilityCapGap,true)}</b></div></div><div className="formula-note"><strong>Visible logic:</strong> payment-day delta × revenue drives receivable; carrying-cost rate drives financing burden; inventory + NCNR × forecast reduction drives stranded inventory; unrecovered portion drives termination exposure.</div></>}</section></div>
}

function Approvals(){const rows=[["Helios Systems","Liability cap","$28M modeled claim vs. $15M cap","GC / CFO","Escalate"],["Apex Mobility","E&O recovery","$9.6M stranded inventory scenario","BU President / Finance","Negotiate"],["Northstar Home","Net 90 terms","$3.1M annual carrying-cost burden","Finance","Negotiate"],["Apex Mobility","Termination coverage","35% recovery assumption","BU President","Escalate"]]; return <section className="panel"><div className="page-title"><div><div className="eyebrow">DECISION QUEUE</div><h1>Approvals and escalations</h1><p>Make the exception, economic consequence and authority visible in one place.</p></div></div><div className="approval-list">{rows.map(r=><div className="approval-card" key={r[0]+r[1]}><div><strong>{r[0]}</strong><span>{r[1]}</span></div><p>{r[2]}</p><div><small>Required</small><b>{r[3]}</b></div><button className={r[4]==="Escalate"?"danger-button":"secondary"}>{r[4]}</button></div>)}</div></section>}

export default function Cockpit(){
 const [view,setView]=useState<View>("overview"); const [matters,setMatters]=useState<Matter[]>(seedMatters);
 useEffect(()=>{try{const saved=localStorage.getItem("ems-cockpit-matters");if(saved)setMatters(JSON.parse(saved))}catch{}},[]);
 const addMatter=(m:Matter)=>setMatters(prev=>{const next=[m,...prev];localStorage.setItem("ems-cockpit-matters",JSON.stringify(next));return next}); const currentTitle=useMemo(()=>nav.find(([id])=>id===view)?.[1]||"Overview",[view]);
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">CT</div><div><strong>ContractTwin</strong><span>Commercial Legal Cockpit</span></div></div><nav>{nav.map(([id,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><span className="nav-dot"/>{label}</button>)}</nav><div className="sidebar-foot"><span>Prototype mode</span><small>Synthetic data · browser-local matter storage</small></div></aside><section className="workspace"><header><span className="breadcrumb">ContractTwin / {currentTitle}</span><div className="header-right"><span className="status-dot"/>Human-controlled analysis<div className="avatar">CG</div></div></header><div className="content">{view==="overview"&&<Overview matters={matters} onNavigate={setView}/>} {view==="matters"&&<Matters matters={matters}/>} {view==="intake"&&<Intake addMatter={addMatter}/>} {view==="risk"&&<RiskAnalyzer/>} {view==="economics"&&<Economics/>} {view==="approvals"&&<Approvals/>}</div><footer>Illustrative prototype using synthetic data. Not legal, accounting or investment advice. Do not use confidential agreements until authentication, secure storage and enterprise controls are configured.</footer></section></main>
}
