"use client";

import { useEffect, useMemo, useState } from "react";

type Risk="Low"|"Medium"|"High"|"Critical";
type Matter={id:string;matterNumber:string;customer:string;agreement:string;region:string;revenue:number;stage:string;risk:Risk;nextAction:string;restricted?:boolean;status?:string};
type Decision={id:string;matter_id:string;matter_number:string;customer:string;decision_type:string;rationale:string;decision_status:string;required_approver_role:string|null;requested_at:string};
const demoMatters:Matter[]=[
{id:"demo-apex",matterNumber:"CT-DEMO-001",customer:"Apex Mobility",agreement:"Global Manufacturing Services Agreement",region:"Americas",revenue:248000000,stage:"Customer redline",risk:"High",nextAction:"Resolve E&O and termination inventory"},
{id:"demo-helios",matterNumber:"CT-DEMO-002",customer:"Helios Systems",agreement:"Strategic Supply Agreement",region:"EMEA",revenue:132000000,stage:"Negotiation",risk:"Critical",nextAction:"Escalate liability cap and warranty tail"},
{id:"demo-northstar",matterNumber:"CT-DEMO-003",customer:"Northstar Home",agreement:"EMS Master Agreement",region:"Americas",revenue:88000000,stage:"Renewal",risk:"Medium",nextAction:"Reprice payment-term economics"}
];
const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1}).format(v);
function Badge({risk}:{risk:Risk}){return <span className={`risk risk-${risk.toLowerCase()}`}>{risk}</span>}

export default function Cockpit(){
 const [matters,setMatters]=useState<Matter[]>([]);const [decisions,setDecisions]=useState<Decision[]>([]);const [readiness,setReadiness]=useState<any>(null);const [mode,setMode]=useState<"database"|"demo">("demo");const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [creating,setCreating]=useState(false);
 const [form,setForm]=useState({customer:"",agreement:"",region:"Americas",revenue:"100000000",restricted:false});
 const refresh=async()=>{setLoading(true);setMessage("");try{const [m,d,r]=await Promise.all([fetch("/api/matters",{cache:"no-store"}),fetch("/api/decisions",{cache:"no-store"}),fetch("/api/readiness",{cache:"no-store"})]);const mj=await m.json();const dj=await d.json();const rj=await r.json();if(!m.ok)throw new Error(mj.error||"Unable to load matters.");const nextMode=mj.mode==="database"?"database":"demo";setMode(nextMode);setMatters(nextMode==="database"?mj.matters:demoMatters);setDecisions(d.ok?(dj.decisions||[]):[]);setReadiness(r.ok?rj.readiness:null);}catch(e){setMessage(e instanceof Error?e.message:"Unable to load cockpit.");}finally{setLoading(false)}};
 useEffect(()=>{void refresh()},[]);
 const metrics=useMemo(()=>({revenue:matters.reduce((s,m)=>s+m.revenue,0),critical:matters.filter(m=>m.risk==="Critical"||m.risk==="High").length,pending:decisions.filter(d=>d.decision_status==="PENDING").length,restricted:matters.filter(m=>m.restricted).length}),[matters,decisions]);
 const createMatter=async(e:React.FormEvent)=>{e.preventDefault();setMessage("");const r=await fetch("/api/matters",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,revenue:Number(form.revenue)})});const j=await r.json();if(!r.ok){setMessage(j.error||"Matter creation failed.");return;}setCreating(false);setForm({customer:"",agreement:"",region:"Americas",revenue:"100000000",restricted:false});await refresh();};
 const gate=readiness?.legalRelianceReady;
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark">CT</div><div><strong>ContractTwin</strong><span>Commercial Legal Cockpit</span></div></div><nav><a className="active" href="#portfolio">Portfolio</a><a href="#decisions">Decisions</a><a href="#readiness">Governance</a><a href="/sign-in">Identity</a></nav><div className="sidebar-footer"><span className={`status-dot ${mode}`}></span>{mode==="database"?"Production data mode":"Synthetic demo mode"}</div></aside>
  <main className="main-content">
   <header className="topbar"><div><div className="eyebrow">EXECUTIVE CONTROL CENTER</div><h1>Commercial legal risk, translated into operating economics.</h1><p>Prioritize agreements, validate source-grounded contract intelligence, and make exceptions through explicit authority gates.</p></div><div className="top-actions"><button className="secondary" onClick={()=>void refresh()}>{loading?"Refreshing…":"Refresh"}</button><button className="primary" disabled={mode!=="database"} onClick={()=>setCreating(v=>!v)}>New matter</button></div></header>
   {message&&<div className="notice">{message}</div>}
   {creating&&<form className="panel form-grid" onSubmit={createMatter}><label>Customer<input value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})}/></label><label>Agreement title<input value={form.agreement} onChange={e=>setForm({...form,agreement:e.target.value})}/></label><label>Region<select value={form.region} onChange={e=>setForm({...form,region:e.target.value})}><option>Americas</option><option>EMEA</option><option>APAC</option></select></label><label>Annual revenue<input type="number" value={form.revenue} onChange={e=>setForm({...form,revenue:e.target.value})}/></label><label className="check"><input type="checkbox" checked={form.restricted} onChange={e=>setForm({...form,restricted:e.target.checked})}/>Restricted matter</label><button className="primary" type="submit">Create secure matter</button></form>}
   <section className="metrics-grid"><div className="metric"><span>Revenue under review</span><strong>{money(metrics.revenue)}</strong><small>{matters.length} accessible matters</small></div><div className="metric warn"><span>High / critical</span><strong>{metrics.critical}</strong><small>Executive attention</small></div><div className="metric"><span>Pending decisions</span><strong>{metrics.pending}</strong><small>Authority queue</small></div><div className="metric"><span>Restricted matters</span><strong>{metrics.restricted}</strong><small>Matter membership required</small></div></section>
   <section className="two-col" id="portfolio"><div className="panel"><div className="panel-head"><div><div className="eyebrow">PORTFOLIO</div><h2>Contract matters</h2></div><span className="filter-chip">{mode==="database"?"Live application state":"Synthetic data"}</span></div><div className="table-wrap"><table><thead><tr><th>Matter</th><th>Customer / agreement</th><th>Revenue</th><th>Stage</th><th>Risk</th><th>Next action</th></tr></thead><tbody>{matters.map(m=><tr key={m.id}><td><strong>{m.matterNumber}</strong><small>{m.region}</small></td><td><strong>{m.customer}</strong><small>{m.agreement}</small></td><td>{money(m.revenue)}</td><td>{m.stage}</td><td><Badge risk={m.risk}/></td><td>{mode==="database"?<a className="workspace-link" href={`/matters/${m.id}`}>{m.nextAction} →</a>:m.nextAction}</td></tr>)}</tbody></table></div></div>
    <aside className="panel" id="readiness"><div className="eyebrow">PRODUCTION GATE</div><h2>{gate?"Legal reliance ready":"Controls still blocking reliance"}</h2>{readiness?<div className="readiness-list"><Row label="Entra SSO" ok={readiness.configured?.microsoftConfigured&&readiness.configured?.authenticationRequired}/><Row label="PostgreSQL" ok={readiness.configured?.databaseConfigured}/><Row label="Private source storage" ok={readiness.configured?.privateBlobConfigured}/><Row label="AI service" ok={readiness.configured?.aiConfigured}/><Row label="OCR service" ok={readiness.configured?.ocrConfigured}/><Row label="Current validation" ok={readiness.validationPassed}/><Row label="Approved standards coverage" ok={(readiness.missingStandards?.length||0)===0}/></div>:<p className="subtle">Readiness unavailable.</p>}<p className="subtle">The legal-reliance switch cannot make the system ready by itself. Current model/prompt/corpus validation and approved standards are enforced separately.</p></aside>
   </section>
   <section className="panel" id="decisions"><div className="panel-head"><div><div className="eyebrow">AUTHORITY QUEUE</div><h2>Pending executive decisions</h2></div></div>{decisions.filter(d=>d.decision_status==="PENDING").length?<div className="approval-list">{decisions.filter(d=>d.decision_status==="PENDING").slice(0,12).map(d=><div className="approval-card" key={d.id}><div><strong>{d.customer}</strong><span>{d.decision_type}</span></div><p>{d.rationale}</p><div><small>Required</small><b>{d.required_approver_role||"APPROVER"}</b></div><a className="secondary" href={`/matters/${d.matter_id}`}>Open matter</a></div>)}</div>:<p className="subtle">No pending decisions visible to this user.</p>}</section>
   <footer className="app-footer">ContractTwin does not autonomously approve terms, alter source agreements, send redlines, or make binding commitments.</footer>
  </main>
 </div>;
}

function Row({label,ok}:{label:string;ok:boolean}){return <div className="readiness-row"><span>{label}</span><b className={ok?"ready":"blocked"}>{ok?"READY":"BLOCKED"}</b></div>}
