"use client";
import { useState } from "react";

export default function DecisionRequestPanel({matterId}:{matterId:string}){
  const [decisionType,setDecisionType]=useState("Contract deviation approval");const [rationale,setRationale]=useState("");const [conditions,setConditions]=useState("");const [role,setRole]=useState("APPROVER");const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setStatus("");const r=await fetch("/api/decision-requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({matterId,decisionType,rationale,conditions,requiredApproverRole:role})});const j=await r.json().catch(()=>({}));setStatus(r.ok?`Decision request ${j.decisionId} created and routed to ${j.requiredApproverRole}.`:j.error||"Decision request failed.");if(r.ok){setRationale("");setConditions("");setTimeout(()=>window.location.reload(),650);}setBusy(false);};
  return <section style={{maxWidth:1600,margin:"10px auto 0",padding:"0 30px"}}><details style={{background:"white",border:"1px solid #e0e5ea",borderRadius:12,padding:"12px 16px"}}><summary style={{cursor:"pointer",fontWeight:800,fontSize:13}}>Request executive / exception decision</summary><p style={hint}>A recommendation is not an approval. This creates a separate pending authority record that an authorized Approver or Admin must disposition.</p><form onSubmit={submit} style={{display:"grid",gridTemplateColumns:"1fr 2fr 2fr 150px auto",gap:9,alignItems:"end"}}><Field label="Decision type"><input required value={decisionType} onChange={e=>setDecisionType(e.target.value)}/></Field><Field label="Rationale"><input required value={rationale} onChange={e=>setRationale(e.target.value)} placeholder="Business/legal reason and consequence"/></Field><Field label="Conditions / guardrails"><input value={conditions} onChange={e=>setConditions(e.target.value)} placeholder="Optional conditions of approval"/></Field><Field label="Authority"><select value={role} onChange={e=>setRole(e.target.value)}><option>APPROVER</option><option>ADMIN</option></select></Field><button disabled={busy||!rationale.trim()} style={primary}>{busy?"Routing…":"Create request"}</button></form>{status&&<p style={{fontSize:11,color:"#6b5423"}}>{status}</p>}</details></section>;
}
const primary:React.CSSProperties={background:"#17212b",color:"white",border:0,borderRadius:8,padding:"9px 12px",fontWeight:800};const hint:React.CSSProperties={fontSize:11,color:"#74808a"};
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{fontSize:10,fontWeight:800,color:"#53616e"}}>{label}<div style={{marginTop:4}}>{children}</div><style jsx>{`input,select{width:100%;box-sizing:border-box;padding:8px;border:1px solid #d5dce3;border-radius:7px;font:inherit}`}</style></label>}
