"use client";
import { useEffect,useState } from "react";

const base={annualRevenue:0,grossMarginPct:8,paymentDays:60,baselinePaymentDays:45,carryingCostPct:10,inventoryOnHand:0,ncnrExposure:0,forecastReductionPct:0,warrantyRatePct:.5,terminationCoveragePct:100,liabilityCap:0,modeledClaim:0};
const fields:[keyof typeof base,string,string][]=[["annualRevenue","Annual revenue","$"],["grossMarginPct","Gross margin","%"],["paymentDays","Customer payment days","days"],["baselinePaymentDays","Baseline payment days","days"],["carryingCostPct","Carrying cost","%"],["inventoryOnHand","Inventory on hand","$"],["ncnrExposure","NCNR commitments","$"],["forecastReductionPct","Forecast reduction scenario","%"],["warrantyRatePct","Warranty reserve rate","%"],["terminationCoveragePct","Termination recovery coverage","%"],["liabilityCap","Liability cap","$"],["modeledClaim","Modeled claim","$"]];
const money=(v:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:2}).format(v);
export default function EconomicsRunPanel({matterId}:{matterId:string}){
 const [input,setInput]=useState(base);const [result,setResult]=useState<any>(null);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{void(async()=>{const r=await fetch(`/api/matters/${matterId}/workspace`,{cache:"no-store"});const j=await r.json();if(r.ok)setInput(p=>({...p,annualRevenue:Number(j.matter?.annual_revenue||0)}));})()},[matterId]);
 const run=async()=>{setBusy(true);setStatus("");const r=await fetch("/api/economics",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({matterId,inputs:input})});const j=await r.json();if(r.ok){setResult(j.result);setStatus(`Persisted ${j.formulaVersion}. Reload the matter workspace to include this run in snapshots.`);}else setStatus(j.error||"Economics run failed.");setBusy(false);};
 return <section style={{maxWidth:1600,margin:"10px auto 0",padding:"0 30px"}}><details style={{background:"white",border:"1px solid #e0e5ea",borderRadius:12,padding:"12px 16px"}}><summary style={{cursor:"pointer",fontWeight:800,fontSize:13}}>Run deterministic contract economics</summary><p style={hint}>These are business assumptions and contract facts supplied by the user. Ordinary software performs the calculations; the language model does not calculate the financial outputs.</p><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(150px,1fr))",gap:9}}>{fields.map(([key,label,unit])=><label key={key} style={{fontSize:10,fontWeight:800,color:"#53616e"}}>{label}<div style={{display:"flex",alignItems:"center",gap:4,marginTop:4}}><input type="number" step="any" value={input[key]} onChange={e=>setInput(p=>({...p,[key]:Number(e.target.value)}))} style={control}/><span style={{fontSize:10,color:"#7b8792"}}>{unit}</span></div></label>)}</div><button disabled={busy} onClick={()=>void run()} style={primary}>{busy?"Calculating…":"Calculate and persist scenario"}</button>{result&&<div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:8,marginTop:12}}>{[["Total modeled burden",money(result.totalModeledBurden)],["Working-capital cost",money(result.workingCapitalCost)],["Termination exposure",money(result.terminationExposure)],["Liability-cap gap",money(result.liabilityCapGap)]].map(([k,v])=><div key={k} style={metric}><span style={{fontSize:9,color:"#75818c",textTransform:"uppercase"}}>{k}</span><b style={{display:"block",fontSize:18,marginTop:3}}>{v}</b></div>)}</div>}{status&&<p style={{fontSize:11,color:"#6b5423"}}>{status}</p>}</details></section>;
}
const control:React.CSSProperties={width:"100%",boxSizing:"border-box",padding:7,border:"1px solid #d6dde4",borderRadius:7};const primary:React.CSSProperties={marginTop:12,background:"#17212b",color:"white",border:0,borderRadius:8,padding:"9px 12px",fontWeight:800};const metric:React.CSSProperties={border:"1px solid #e2e7eb",borderRadius:8,padding:9};const hint:React.CSSProperties={fontSize:11,color:"#74808a"};
