"use client";
import { useEffect,useState } from "react";

export default function GovernancePanel({matterId}:{matterId:string}){
 const [data,setData]=useState<any>(null);const [message,setMessage]=useState("");const [reason,setReason]=useState("");const [busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch(`/api/matters/${matterId}/governance`,{cache:"no-store"});const j=await r.json();if(r.ok)setData(j);else setMessage(j.error||"Unable to load governance.");};
 useEffect(()=>{void load()},[matterId]);
 const patch=async(body:any)=>{setBusy(true);setMessage("");const r=await fetch(`/api/matters/${matterId}/governance`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));setMessage(r.ok?"Governance state updated.":j.error||"Governance update failed.");setBusy(false);if(r.ok){setReason("");await load();}};
 if(!data)return null;const g=data.governance;
 return <section style={{maxWidth:1600,margin:"10px auto 0",padding:"0 30px"}}><details style={{background:"white",border:"1px solid #e0e5ea",borderRadius:12,padding:"12px 16px"}}><summary style={{cursor:"pointer",fontWeight:800,fontSize:13}}>Records governance · {g.confidentiality_level} · {g.privilege_status} · {g.legal_hold?"LEGAL HOLD":"No hold"}</summary><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:10,marginTop:14}}><Field label="Confidentiality"><select value={g.confidentiality_level} onChange={e=>void patch({confidentialityLevel:e.target.value})}>{["INTERNAL","CONFIDENTIAL","PRIVILEGED","RESTRICTED"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Privilege"><select value={g.privilege_status} onChange={e=>void patch({privilegeStatus:e.target.value})}>{["NOT_ASSESSED","PRIVILEGED","WORK_PRODUCT","NON_PRIVILEGED","MIXED"].map(v=><option key={v}>{v}</option>)}</select></Field><Field label="Retention category"><input defaultValue={g.retention_category||""} onBlur={e=>void patch({retentionCategory:e.target.value||null})} placeholder="Company policy category"/></Field><Field label="Retention through"><input type="date" defaultValue={g.retention_until?String(g.retention_until).slice(0,10):""} onBlur={e=>void patch({retentionUntil:e.target.value||null})}/></Field></div><div style={{display:"flex",gap:8,alignItems:"end",marginTop:12}}><Field label={g.legal_hold?"Reason to release hold":"Reason to apply hold"}><input value={reason} onChange={e=>setReason(e.target.value)} placeholder="Required legal records reason"/></Field><button disabled={busy||!reason.trim()} onClick={()=>void patch({legalHold:!g.legal_hold,legalHoldReason:reason})} style={{padding:"8px 11px",borderRadius:7,border:"1px solid #cbd4dc",background:g.legal_hold?"#fff2e8":"#17212b",color:g.legal_hold?"#8a4d22":"white",fontWeight:800}}>{g.legal_hold?"Release hold (Approver)":"Apply legal hold"}</button></div>{g.legal_hold_reason&&<p style={{fontSize:11,color:"#697683"}}>Current hold reason: {g.legal_hold_reason}</p>}{message&&<p style={{fontSize:11,color:"#7a4d2e"}}>{message}</p>}<div style={{marginTop:10,fontSize:11,color:"#74808a"}}>Retention periods are not invented by ContractTwin. They must reflect the company's approved records policy. Source purge remains separately approved and disabled by default.</div></details></section>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label style={{fontSize:11,fontWeight:700,flex:1}}>{label}<div style={{marginTop:5}}>{children}</div><style jsx>{`input,select{width:100%;box-sizing:border-box;padding:8px;border:1px solid #d5dce3;border-radius:7px;font:inherit}`}</style></label>}
