"use client";
import { useEffect,useState } from "react";

export default function MatterAccessPanel({matterId}:{matterId:string}){
 const [data,setData]=useState<any>({members:[],directory:[],canAdmin:false});const [userId,setUserId]=useState("");const [level,setLevel]=useState("VIEW");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 const load=async()=>{const r=await fetch(`/api/matters/${matterId}/members`,{cache:"no-store"});const j=await r.json();if(r.ok){setData(j);if(!userId&&j.directory?.[0]?.user_id)setUserId(j.directory[0].user_id);}else setMessage(j.error||"Unable to load matter access.");};useEffect(()=>{void load()},[matterId]);
 const grant=async()=>{if(!userId)return;setBusy(true);const r=await fetch(`/api/matters/${matterId}/members`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId,accessLevel:level})});const j=await r.json();setMessage(r.ok?"Matter access updated.":j.error||"Access update failed.");setBusy(false);if(r.ok)await load();};
 const remove=async(id:string)=>{setBusy(true);const r=await fetch(`/api/matters/${matterId}/members?userId=${encodeURIComponent(id)}`,{method:"DELETE"});const j=await r.json();setMessage(r.ok?"Matter access removed.":j.error||"Access removal failed.");setBusy(false);if(r.ok)await load();};
 return <section style={{maxWidth:1600,margin:"10px auto 0",padding:"0 30px"}}><details style={{background:"white",border:"1px solid #e0e5ea",borderRadius:12,padding:"12px 16px"}}><summary style={{cursor:"pointer",fontWeight:800,fontSize:13}}>Matter access · {data.members.length} explicit member{data.members.length===1?"":"s"}</summary><div style={{display:"grid",gridTemplateColumns:"1.2fr 1fr",gap:18,marginTop:14}}><div><b style={{fontSize:12}}>Current members</b>{data.members.length?data.members.map((m:any)=><div key={m.user_id} style={{display:"flex",justifyContent:"space-between",gap:10,borderBottom:"1px solid #edf0f2",padding:"8px 0",fontSize:11}}><div><b>{m.name||m.email||m.user_id}</b><div style={{color:"#74808a"}}>{m.email||m.user_id}</div></div><div style={{display:"flex",gap:8,alignItems:"center"}}><span>{m.access_level}</span>{data.canAdmin&&<button disabled={busy} onClick={()=>void remove(m.user_id)}>Remove</button>}</div></div>):<p style={{fontSize:11,color:"#74808a"}}>No explicit members. Restricted matters remain available to the owner and Admins.</p>}</div>{data.canAdmin?<div><b style={{fontSize:12}}>Grant or change access</b><label style={label}>Authenticated user<select value={userId} onChange={e=>setUserId(e.target.value)} style={control}><option value="">Select</option>{data.directory.map((u:any)=><option value={u.user_id} key={u.user_id}>{u.name||u.email} · {u.role}</option>)}</select></label><label style={label}>Access level<select value={level} onChange={e=>setLevel(e.target.value)} style={control}><option>VIEW</option><option>EDIT</option><option>APPROVE</option></select></label><button disabled={busy||!userId} onClick={()=>void grant()} style={primary}>Save matter access</button></div>:<p style={{fontSize:11,color:"#74808a"}}>Only the matter owner or an Admin can modify membership.</p>}</div>{message&&<p style={{fontSize:11,color:"#7a4d2e"}}>{message}</p>}</details></section>;
}
const label:React.CSSProperties={display:"block",fontSize:11,fontWeight:700,marginTop:9};const control:React.CSSProperties={display:"block",width:"100%",boxSizing:"border-box",padding:8,marginTop:4,border:"1px solid #d5dce3",borderRadius:7};const primary:React.CSSProperties={background:"#17212b",color:"white",border:0,borderRadius:8,padding:"9px 12px",fontWeight:800,marginTop:10};
