"use client";

import { useEffect, useMemo, useState } from "react";
import styles from "./MatterWorkspace.module.css";

type Tab="sources"|"twin"|"precedence"|"findings"|"economics"|"decisions"|"versions"|"audit";
type Workspace=Record<string,any>;
const money=(v:any)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",notation:"compact",maximumFractionDigits:1}).format(Number(v)||0);
const tabs:[Tab,string][]=[["sources","Source Set"],["twin","Contract Twin"],["precedence","Precedence"],["findings","Findings"],["economics","Economics"],["decisions","Decisions"],["versions","Versions"],["audit","Audit"]];

export default function MatterWorkspace({matterId}:{matterId:string}){
  const [data,setData]=useState<Workspace|null>(null);const [tab,setTab]=useState<Tab>("sources");const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  const [versionLabel,setVersionLabel]=useState("Working agreement set");const [selectedDocs,setSelectedDocs]=useState<string[]>([]);
  const [relation,setRelation]=useState({sourceDocumentId:"",targetDocumentId:"",relationType:"CONTROLS",rationale:""});
  const refresh=async()=>{setLoading(true);try{const r=await fetch(`/api/matters/${matterId}/workspace`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.error||"Unable to load workspace.");setData(j);if(!selectedDocs.length)setSelectedDocs((j.documents||[]).map((d:any)=>d.id));}catch(e){setMessage(e instanceof Error?e.message:"Unable to load workspace.");}finally{setLoading(false)}};
  useEffect(()=>{void refresh()},[matterId]);
  const mutate=async(url:string,options:RequestInit,success:string)=>{setMessage("");const r=await fetch(url,options);const j=await r.json().catch(()=>({}));if(!r.ok){setMessage(j.error||"Action failed.");return false;}setMessage(success);await refresh();return true;};
  const startPipeline=(id:string)=>mutate(`/api/documents/${id}/pipeline`,{method:"POST"},"Durable ContractTwin pipeline started.");
  const reviewFinding=(id:string,status:string)=>mutate(`/api/findings/${id}/review`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})},`Finding ${status.toLowerCase()}.`);
  const reviewGraph=(entityType:string,id:string,action:string)=>mutate(`/api/graph/review`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({entityType,id,action})},`Graph object ${action.toLowerCase()}d.`);
  const decide=(id:string,status:string)=>mutate(`/api/decisions/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})},`Decision ${status.toLowerCase()}.`);
  const createVersion=()=>mutate(`/api/matters/${matterId}/versions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({label:versionLabel,documentIds:selectedDocs})},"Agreement version frozen.");
  const changeVersion=(id:string,status:string)=>mutate(`/api/agreement-versions/${id}/status`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})},`Agreement version marked ${status}.`);
  const createRelation=async()=>{const ok=await mutate(`/api/matters/${matterId}/relations`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(relation)},"Document relationship recorded and validated.");if(ok)setRelation(v=>({...v,rationale:""}));};
  const latestEcon=data?.economicsRuns?.[0];
  const metrics=useMemo(()=>{
    if(!data)return [];
    return [["Documents",data.documents?.length||0],["Validated findings",data.findings?.filter((f:any)=>f.review_status==="VALIDATED").length||0],["Unreviewed terms",data.terms?.filter((t:any)=>t.review_status==="UNREVIEWED").length||0],["Pending decisions",data.decisions?.filter((d:any)=>d.decision_status==="PENDING").length||0]];
  },[data]);
  if(loading&&!data)return <main className={styles.loading}>Loading secure matter workspace…</main>;
  if(!data)return <main className={styles.loading}><p>{message||"Matter workspace unavailable."}</p><a href="/">Return to cockpit</a></main>;
  const m=data.matter;
  return <main className={styles.shell}>
    <header className={styles.header}><div><a className={styles.back} href="/">← Executive cockpit</a><div className={styles.eyebrow}>MATTER WORKSPACE · {m.matter_number}</div><h1>{m.customer}</h1><p>{m.agreement_title} · {m.region}</p></div><div className={styles.headerRight}><span className={styles.role}>{data.principal?.role}</span><button onClick={()=>void refresh()}>Refresh</button></div></header>
    <section className={styles.metrics}>{metrics.map(([k,v])=><div key={String(k)}><span>{k}</span><strong>{v}</strong></div>)}<div><span>Revenue</span><strong>{money(m.annual_revenue)}</strong></div></section>
    {message&&<div className={styles.message}>{message}</div>}
    <nav className={styles.tabs}>{tabs.map(([id,label])=><button key={id} className={tab===id?styles.active:""} onClick={()=>setTab(id)}>{label}</button>)}</nav>

    {tab==="sources"&&<section className={styles.grid}>
      <div className={styles.panel}><div className={styles.panelHead}><div><span className={styles.eyebrow}>SOURCE OF TRUTH</span><h2>Agreement documents</h2></div><span>{data.documents.length} files</span></div>
        <div className={styles.cards}>{data.documents.map((d:any)=><article key={d.id} className={styles.card}><div className={styles.cardTop}><div><b>{d.filename}</b><small>{d.document_type}{d.version_label?` · ${d.version_label}`:""}</small></div><span className={styles.status}>{d.extraction_status}</span></div><dl><dt>Integrity</dt><dd>{d.integrity_status}</dd><dt>Pages</dt><dd>{d.page_count??"—"}</dd><dt>Source state</dt><dd>{d.source_status}</dd></dl><button className={styles.primary} onClick={()=>void startPipeline(d.id)}>Run full ContractTwin pipeline</button></article>)}</div>
      </div>
      <aside className={styles.panel}><span className={styles.eyebrow}>PIPELINE</span><h2>Processing history</h2>{data.jobs.length?data.jobs.slice(0,12).map((j:any)=><div className={styles.line} key={j.id}><div><b>{j.job_type}</b><small>{j.document_id?"Document stage":"Matter stage"}</small></div><span>{j.status}</span></div>):<p className={styles.muted}>No processing jobs yet.</p>}</aside>
    </section>}

    {tab==="twin"&&<section className={styles.grid}>
      <div className={styles.panel}><span className={styles.eyebrow}>NORMALIZED CONTRACT LOGIC</span><h2>Atomic terms</h2>{data.terms.length?data.terms.map((t:any)=><article className={styles.term} key={t.id}><div className={styles.cardTop}><div><b>{t.clause_family}</b><small>{t.filename}{t.page_number?` · p. ${t.page_number}`:""} · {t.term_type}</small></div><span className={styles.status}>{t.review_status}</span></div><p>{t.normalized_statement}</p><blockquote>{t.exact_text}</blockquote><div className={styles.actions}><button onClick={()=>void reviewGraph("TERM",t.id,"VALIDATE")}>Validate</button><button onClick={()=>void reviewGraph("TERM",t.id,"REJECT")}>Reject</button></div></article>):<p className={styles.muted}>Run the full pipeline to build the atomic contract model.</p>}</div>
      <aside className={styles.panel}><span className={styles.eyebrow}>DEPENDENCY GRAPH</span><h2>Operational edges</h2>{data.dependencies.length?data.dependencies.map((d:any)=><article className={styles.edge} key={d.id}><b>{d.dependency_type}</b><p>{d.rationale}</p><small>{Math.round(Number(d.confidence)*100)}% confidence · {d.review_status}</small><div className={styles.actions}><button onClick={()=>void reviewGraph("DEPENDENCY",d.id,"VALIDATE")}>Validate</button><button onClick={()=>void reviewGraph("DEPENDENCY",d.id,"REJECT")}>Reject</button></div></article>):<p className={styles.muted}>No dependency edges yet.</p>}</aside>
    </section>}

    {tab==="precedence"&&<section className={styles.grid}>
      <div className={styles.panel}><span className={styles.eyebrow}>DOCUMENT HIERARCHY</span><h2>Precedence and lineage</h2>{data.documentRelations.length?data.documentRelations.map((r:any)=><article className={styles.edge} key={r.id}><div className={styles.cardTop}><b>{r.source_document} → {r.target_document}</b><span className={styles.status}>{r.review_status}</span></div><strong>{r.relation_type}</strong><p>{r.rationale}</p><small>{r.source_locator||"No locator"}</small><div className={styles.actions}><button onClick={()=>void reviewGraph("DOCUMENT_RELATION",r.id,"VALIDATE")}>Validate</button><button onClick={()=>void reviewGraph("DOCUMENT_RELATION",r.id,"REJECT")}>Reject</button></div></article>):<p className={styles.muted}>No source-grounded document relationships yet.</p>}</div>
      <aside className={styles.panel}><span className={styles.eyebrow}>COUNSEL OVERRIDE</span><h2>Record relationship</h2><label>Source document<select value={relation.sourceDocumentId} onChange={e=>setRelation({...relation,sourceDocumentId:e.target.value})}><option value="">Select</option>{data.documents.map((d:any)=><option value={d.id} key={d.id}>{d.filename}</option>)}</select></label><label>Relationship<select value={relation.relationType} onChange={e=>setRelation({...relation,relationType:e.target.value})}>{["AMENDS","SUPERSEDES","INCORPORATES","CONTROLS","CONFLICTS_WITH","IMPLEMENTS","REFERENCES"].map(v=><option key={v}>{v}</option>)}</select></label><label>Target document<select value={relation.targetDocumentId} onChange={e=>setRelation({...relation,targetDocumentId:e.target.value})}><option value="">Select</option>{data.documents.map((d:any)=><option value={d.id} key={d.id}>{d.filename}</option>)}</select></label><label>Legal rationale<textarea value={relation.rationale} onChange={e=>setRelation({...relation,rationale:e.target.value})}/></label><button className={styles.primary} onClick={()=>void createRelation()}>Record validated relationship</button></aside>
    </section>}

    {tab==="findings"&&<section className={styles.panel}><span className={styles.eyebrow}>LEGAL REVIEW QUEUE</span><h2>Source-grounded findings</h2><div className={styles.cards}>{data.findings.map((f:any)=><article className={styles.card} key={f.id}><div className={styles.cardTop}><div><b>{f.issue}</b><small>{f.clause_family} · {f.source_locator}</small></div><span className={`${styles.status} ${styles[f.risk_level?.toLowerCase()]||""}`}>{f.risk_level}</span></div><p>{f.rationale}</p><blockquote>{f.source_excerpt}</blockquote><dl><dt>Standard</dt><dd>{f.standard_status}{f.standard_version?` · ${f.standard_version}`:""}</dd><dt>Primary</dt><dd>{f.primary_position||"No approved standard"}</dd><dt>Approval</dt><dd>{f.approval_required||"—"}</dd></dl><div className={styles.actions}><button onClick={()=>void reviewFinding(f.id,"VALIDATED")}>Validate</button><button onClick={()=>void reviewFinding(f.id,"REJECTED")}>Reject</button></div></article>)}</div></section>}

    {tab==="economics"&&<section className={styles.grid}><div className={styles.panel}><span className={styles.eyebrow}>DETERMINISTIC ECONOMICS</span><h2>Latest modeled exposure</h2>{latestEcon?<><div className={styles.heroNumber}>{money(latestEcon.outputs?.totalModeledBurden)}</div><p>{Number(latestEcon.outputs?.burdenAsPctOfGrossProfit||0).toFixed(1)}% of modeled gross profit · formula {latestEcon.formula_version}</p><div className={styles.kv}>{Object.entries(latestEcon.outputs||{}).filter(([,v])=>typeof v==="number").map(([k,v])=><div key={k}><span>{k.replaceAll(/([A-Z])/g," $1")}</span><b>{k.includes("Pct")?`${Number(v).toFixed(1)}%`:money(v)}</b></div>)}</div></>:<p className={styles.muted}>No persisted economics run for this matter.</p>}</div><aside className={styles.panel}><span className={styles.eyebrow}>HISTORY</span><h2>Model versions</h2>{data.economicsRuns.map((r:any)=><div className={styles.line} key={r.id}><div><b>{r.formula_version}</b><small>{new Date(r.created_at).toLocaleString()}</small></div><span>{money(r.outputs?.totalModeledBurden)}</span></div>)}</aside></section>}

    {tab==="decisions"&&<section className={styles.panel}><span className={styles.eyebrow}>AUTHORITY GATE</span><h2>Executive decisions</h2>{data.decisions.map((d:any)=><article className={styles.decision} key={d.id}><div><b>{d.decision_type}</b><p>{d.rationale}</p><small>{d.required_approver_role||"APPROVER"} · {d.decision_status}</small></div>{d.decision_status==="PENDING"&&<div className={styles.actions}><button onClick={()=>void decide(d.id,"APPROVED")}>Approve</button><button onClick={()=>void decide(d.id,"REJECTED")}>Reject</button></div>}</article>)}</section>}

    {tab==="versions"&&<section className={styles.grid}><div className={styles.panel}><span className={styles.eyebrow}>FROZEN AGREEMENT STATE</span><h2>Agreement versions</h2>{data.agreementVersions.map((v:any)=><article className={styles.card} key={v.id}><div className={styles.cardTop}><div><b>v{v.version_number} · {v.label}</b><small>{(v.documents||[]).map((d:any)=>d.filename).join(" · ")}</small></div><span className={styles.status}>{v.status}</span></div><div className={styles.actions}>{v.status==="WORKING"&&<button onClick={()=>void changeVersion(v.id,"APPROVED")}>Approve set</button>}{v.status==="APPROVED"&&<button onClick={()=>void changeVersion(v.id,"EXECUTED")}>Mark executed</button>}{(v.status==="APPROVED"||v.status==="EXECUTED")&&<button onClick={()=>void changeVersion(v.id,"SUPERSEDED")}>Supersede</button>}</div></article>)}</div><aside className={styles.panel}><span className={styles.eyebrow}>NEW VERSION</span><h2>Freeze current source set</h2><label>Label<input value={versionLabel} onChange={e=>setVersionLabel(e.target.value)}/></label><div className={styles.checks}>{data.documents.map((d:any)=><label key={d.id}><input type="checkbox" checked={selectedDocs.includes(d.id)} onChange={e=>setSelectedDocs(p=>e.target.checked?[...p,d.id]:p.filter(x=>x!==d.id))}/>{d.filename}</label>)}</div><button className={styles.primary} onClick={()=>void createVersion()}>Create working version</button></aside></section>}

    {tab==="audit"&&<section className={styles.grid}><div className={styles.panel}><span className={styles.eyebrow}>IMMUTABLE HISTORY</span><h2>Audit trail</h2>{data.audit.map((a:any)=><div className={styles.audit} key={a.id}><time>{new Date(a.event_time).toLocaleString()}</time><b>{a.action}</b><span>{a.actor_name}</span><small>{a.entity_type}{a.entity_id?` · ${a.entity_id}`:""}</small></div>)}</div><aside className={styles.panel}><span className={styles.eyebrow}>EXECUTIVE SNAPSHOTS</span><h2>Decision-ready states</h2>{data.snapshots.map((s:any)=><div className={styles.line} key={s.id}><div><b>Snapshot v{s.snapshot_version}</b><small>{new Date(s.generated_at).toLocaleString()}</small></div><a href={`/matters/${matterId}/executive-summary?snapshot=${s.id}`}>Open</a></div>)}</aside></section>}
  </main>;
}
