"use client";
import { useEffect,useState } from "react";

export default function SourceRecordsPanel({matterId}:{matterId:string}){
 const [data,setData]=useState<any>(null);const [reason,setReason]=useState<Record<string,string>>({});const [message,setMessage]=useState("");const [busy,setBusy]=useState<string|null>(null);
 const load=async()=>{const r=await fetch(`/api/matters/${matterId}/workspace`,{cache:"no-store"});const j=await r.json();if(r.ok)setData(j);else setMessage(j.error||"Unable to load source records.");};useEffect(()=>{void load()},[matterId]);
 const requestPurge=async(documentId:string)=>{const why=(reason[documentId]||"").trim();if(!why)return;setBusy(documentId);const r=await fetch(`/api/documents/${documentId}/purge`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({reason:why})});const j=await r.json();setMessage(r.ok?"Purge request created for independent Admin review.":j.error||"Purge request failed.");setBusy(null);if(r.ok){setReason(p=>({...p,[documentId]:""}));await load();}};
 if(!data)return null;const openByDoc=new Map((data.purgeRequests||[]).filter((p:any)=>["PENDING","APPROVED"].includes(p.status)).map((p:any)=>[p.document_id,p]));
 return <section style={{maxWidth:1600,margin:"10px auto 0",padding:"0 30px"}}><details style={{background:"white",border:"1px solid #e0e5ea",borderRadius:12,padding:"12px 16px"}}><summary style={{cursor:"pointer",fontWeight:800,fontSize:13}}>Source records · retention and controlled purge</summary><p style={{fontSize:11,color:"#74808a"}}>Source destruction is never immediate. A request requires independent Admin approval, no legal hold, an expired retention date, and the separately disabled production purge switch.</p><div style={{display:"grid",gap:9}}>{data.documents.map((d:any)=>{const open=openByDoc.get(d.id) as any;return <article key={d.id} style={{border:"1px solid #e3e8ec",borderRadius:9,padding:11,display:"grid",gridTemplateColumns:"minmax(260px,1fr) 130px 150px minmax(280px,1.2fr)",gap:12,alignItems:"center",fontSize:11}}><div><b>{d.filename}</b><div style={{color:"#74808a"}}>{d.document_type} · {d.deletion_status}</div><a href={`/api/documents/${d.id}/content`} target="_blank" rel="noreferrer" style={{color:"#315f93"}}>View preserved source</a></div><div><span style={muted}>Retention</span><br/>{d.retention_until?String(d.retention_until).slice(0,10):"Not set"}</div><div><span style={muted}>Hold / request</span><br/>{d.legal_hold?"DOCUMENT HOLD":open?open.status:"None"}</div><div>{d.deletion_status!=="ACTIVE"?<span>{d.deletion_status}</span>:open?<span>Open request: <b>{open.status}</b></span>:<div style={{display:"flex",gap:6}}><input value={reason[d.id]||""} onChange={e=>setReason(p=>({...p,[d.id]:e.target.value}))} placeholder="Records-management reason" style={{flex:1,padding:7,border:"1px solid #d5dce3",borderRadius:7}}/><button disabled={busy===d.id||!(reason[d.id]||"").trim()} onClick={()=>void requestPurge(d.id)}>Request purge</button></div>}</div></article>})}</div>{message&&<p style={{fontSize:11,color:"#7a4d2e"}}>{message}</p>}</details></section>;
}
const muted:React.CSSProperties={color:"#74808a",textTransform:"uppercase",fontSize:9,letterSpacing:".07em"};
