-- Illustrative only. These rows are intentionally inactive and must never be treated as approved company policy.
insert into negotiation_standards
  (clause_family,title,standard_position,fallback_position,no_go_position,approval_authority,business_rationale,active,version,effective_date,created_by)
values
('payment_terms','Payment terms','Net 45 or better.','Net 60 with explicit economic recovery.','Terms beyond the approved threshold without Finance approval.','Finance + BU leadership','Extended receivables consume working capital and can materially erode low-margin manufacturing economics.',false,'DEMO-2026-08-07','2026-08-07','seed'),
('excess_obsolete_inventory','Excess and obsolete inventory','Customer purchases inventory and NCNR commitments authorized by forecasts, POs, changes, or termination.','Defined recovery schedule plus carrying charges.','Open-ended manufacturer exposure to customer-driven E&O without recovery mechanism.','Operations + Finance + Legal','Demand volatility and procurement commitments can strand material and working capital.',false,'DEMO-2026-08-07','2026-08-07','seed'),
('liability_cap','Liability cap','Aggregate cap proportionate to contract economics with narrow defined carve-outs.','Negotiated super-cap for specifically identified risks.','General uncapped liability or consequential loss exposure without explicit executive approval.','GC + CFO','Unbounded exposure is disproportionate to EMS margin and may exceed insurance.',false,'DEMO-2026-08-07','2026-08-07','seed'),
('warranty','Warranty','Defined manufacturing-defect warranty with clear duration, exclusions, remedy, and claim process.','Extended duration only with pricing and reserve support.','Broad performance/design warranty outside manufacturing responsibility without approval.','Quality + Finance + Legal','Warranty scope and tail drive reserve, field-cost and attribution risk.',false,'DEMO-2026-08-07','2026-08-07','seed'),
('termination','Termination for convenience','Customer pays committed materials, NCNR, WIP, finished goods, cancellation charges, and agreed wind-down costs.','Longer notice plus scheduled inventory recovery.','Convenience termination that leaves customer-authorized commitments stranded.','BU + Finance + Legal','Termination interacts with forecast authorization, procurement commitments and inventory ownership.',false,'DEMO-2026-08-07','2026-08-07','seed'),
('pricing_repricing','Pricing and repricing','Defined pass-through or repricing mechanics for agreed external cost drivers and scope changes.','Periodic review with objective indices and documented evidence.','Fixed pricing against uncontrolled material, tariff, FX or regulatory-cost changes without approval.','Finance + Commercial + Legal','Unrecoverable external cost movement directly erodes manufacturing margin.',false,'DEMO-2026-08-07','2026-08-07','seed')
on conflict (clause_family,version) do nothing;
